gitRepoUrl = "https://github.com/Breezy1214/Knit"

classOrder = [
	"KnitServer",
	"KnitClient"
]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Lightweight game framework for Roblox"
favicon = "/favicon.png"
