[tools]
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.28.0"
stylua = 'JohnnyMorganz/StyLua@0.20.0'
wally = 'UpliftGames/wally@0.3.2'
luau-lsp = "JohnnyMorganz/luau-lsp@1.39.2"
lune = "lune-org/lune@0.8.9"
rbxcloud = "Sleitnick/rbxcloud@0.15.1"
