[tools]
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
stylua = 'JohnnyMorganz/StyLua@0.20.0'
wally = 'UpliftGames/wally@0.3.2'
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.4"
lune = "lune-org/lune@0.8.8"
rbxcloud = "Sleitnick/rbxcloud@0.14.0"
